// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"nof0-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/account-totals",
				Handler: AccountTotalsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/analytics",
				Handler: AnalyticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/analytics/:modelId",
				Handler: ModelAnalyticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/crypto-prices",
				Handler: CryptoPricesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/leaderboard",
				Handler: LeaderboardHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/since-inception-values",
				Handler: SinceInceptionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/trades",
				Handler: TradesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/positions",
				Handler: PositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations",
				Handler: ConversationsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
